spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-exam
    username: nandor
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

app:
  rootPassword: admin